CREATE DATABASE SAMPLE;

USE SAMPLE;
cREATE table student(regno int,studentname varchar(50),department varchar(50));

describe student;

ALTER TABLE STUDENT ADD COLUMN AGE INT,ADD COLUMN GENDER VARCHAR(2);  

ALTER TABLE STUDENT MODIFY DEPARTMENT VARCHAR(30) after GENDER,MODIFY GENDER VARCHAR(10); 

describe student;

ALTER TABLE STUDENT DROP COLUMN DEPARTMENT,DROP COLUMN GENDER;

describe STUDENT;

ALTER TABLE STUDENT RENAME TO STUDENT_OLD;

DROP TABLE STUDENT_OLD; 

-- RENAME data SAMPLE TO NEWSAMPLE; 
drop database sample;

