CREATE TABLE VOTE(
	VOTER_ID INT PRIMARY KEY,
    VOTER_NAME VARCHAR(50),
    VOTER_AGE INT,
    CONSTRAINT AGE_CHECK CHECK (VOTER_AGE >= 18) 
);
describe VOTE;

INSERT INTO VOTE VALUES(1001,'ANANTH',15);

INSERT INTO VOTE VALUES(1000,'ANANTH',25);

-- ---------------  DROP CHECK CONTRAINTS ---------------
ALTER TABLE VOTE DROP CONSTRAINT vote_chk_1;

ALTER TABLE VOTE ADD CONSTRAINT vote_chk_1 CHECK (VOTER_AGE >= 18) ;

DELETE FROM VOTE WHERE VOTER_ID='1001'; 