CREATE TABLE NOTNULL(
	VOTER_ID INT PRIMARY KEY,
	VOTER_NAME VARCHAR(50) NOT NULL,
	VOTER_AGE INT
);

INSERT INTO NOTNULL (VOTER_ID,VOTER_AGE) VALUES(1001,18); -- //Error Code: 1364. Field 'VOTER_NAME' doesn't have a default value
INSERT INTO NOTNULL (VOTER_ID,VOTER_NAME) VALUES(1001,'ANANTH');

-- IF BEFORE MODIFY NOT NULL ,PLEASE ENSURE TABLE CONTAIN ALL COLUMN ARE NOT NULL
-- IF ONE ATTRIBUTE IS NULL ALTER QUERY DOESN'T WORK
-- Error Code: 1138. Invalid use of NULL value	0.031 sec
ALTER TABLE NOTNULL MODIFY VOTER_AGE INT NOT NULL;

UPDATE NOTNULL SET VOTER_AGE = 23 WHERE VOTER_ID = 1001;
ALTER TABLE NOTNULL MODIFY VOTER_AGE INT NOT NULL;
-- LTER TABLE NOTNULL MODIFY VOTER_AGE INT NOT NULL	0 row(s) affected

-- Error Code: 1138. Invalid use of NULL value	0.031 sec
