CREATE TABLE EMPLOYEE(
	EMP_ID INT NOT NULL,
	EMP_NAME VARCHAR(50) ,
	DOJ DATETIME DEFAULT(NOW())
);

CREATE TABLE EMPLOYEE_1(
	EMP_ID INT NOT NULL,
	EMP_NAME VARCHAR(50) DEFAULT '********' ,
	DOJ DATETIME DEFAULT(NOW())
);


INSERT INTO EMPLOYEE (EMP_ID,EMP_NAME) VALUES (1001,'Ananth');
SELECT * FROM EMPLOYEE;

INSERT INTO EMPLOYEE_1 (EMP_ID) VALUES (1001);
SELECT * FROM EMPLOYEE_1;