set @A=2; -- // @ REPRESENT OUTPUT
call first_procedure(@A);
SELECT COUNT(JOB_ID),SUM(SALARY),avg(SALARY),MAX(SALARY),MIN(SALARY) FROM EMPLOYEE_DETAILS_MAIN GROUP BY JOB_ID ;
CALL EMP_SALARY ('IT PROG', @COUNT_SALARY, @SUM_SALARY, @AVG_SALARY, @MAX_SALARY, @MIN_SALARY);